ASP.NET MVC5 Bootstrap 3.3.1 LESS/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ASP.NET_MVC5_Bootstrap_3._3._1_LESS.Models;
using System.Net;

namespace ASP.NET_MVC5_Bootstrap_3._3._1_LESS.Controllers
{
    public class NewsController : Controller
    {
        private ProjectContext db = new ProjectContext();
        // GET: News
        public ActionResult Index(int page = 1)
        {
            return View(db.Newss.OrderByDescending(news => news.Id).ToList().ToPagedList(pageNumber: page, pageSize: 10));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.Newss.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }
    }
}

ASP.NET MVC5 Bootstrap 3.3.1 LESS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" name="baidu-tc-cerfication" data-appid="5173281" src="http://apps.bdimg.com/cloudaapi/lightapp.js"></script>
    <title>@ViewBag.Title - 新闻发布系统</title>
    <meta name="description" content="MVC5简易新闻发布系统" />
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("新闻发布系统", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("新闻", "Index", "News")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 新闻发布系统</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>